### ISSUE TITLE
Open FAB horizontally instead of vertical

### ISSUE THREAD

**Issue by Kena-khakhkhar-incontact** [dericcain/react-tiny-fab#112]
I am new to this library but I guess the opening direction is fixed(vertical).Is there option to open it horizontally(Like right to left or left to right)? or any suggestion how to do that with css changes?

**Comment by dericcain** [comment]
@Kena-khakhkhar-incontact I am trying to stick close to the Material Guidelines with this FAB implementation and the guidelines do not show a use case for a horizontal FAB. However, it does take a `style` prop and it also passes down props so something like Styled Components could possibly be used to come up with what you want to do. See this code: https://github.com/dericcain/react-tiny-fab/blob/master/src/index.tsx#L111-L112

I am going to close this for now but if you have any questions or get stuck, let me know and I will try and help.

**Comment by hupeky** [comment]
Yes, I have a similar need for having a vertical down use case instead of vertical up.

and am exploring how to edit the code thats there to achieve this. Material ui has a direction prop. making its flexability very nice
