### ISSUE TITLE
FAB can't open after been closed

### ISSUE THREAD

**Issue by ShardanaSoft** [dericcain/react-tiny-fab#93]
Hi, 
once the FAB is been closed it won't open again.

Step to reproduce (this only happens on **mobile** and event='hover')

1) open fab
2) press one of the actions, at this point fab is closed
3) try to open fab again...nothing happen

this bug is unlocked by typing on the background

I think this issue is related to #75 , but he doesn't mention is only about mobile.

You can test it in your [page](https://dericgw.github.io/react-tiny-fab/#components) too

**Comment by dericgw** [comment]
Thanks for bringing this up. Are you saying it's only on mobile?

**Comment by ShardanaSoft** [comment]
> Thanks for bringing this up. Are you saying it's only on mobile?
Yeah it looks like is only mobile fault. 

Sorry I don't have enough knowledge to help you out with this ;(

**Comment by dericcain** [comment]
I hope to have this fixed in #103. If you want to test it out, please do.
