### ISSUE TITLE
button cannot work for second action

### ISSUE THREAD

**Issue by NicKZ-gene** [dericcain/react-tiny-fab#98]
Hi, I found a problem in the Action. 
<img width="384" alt="截屏2021-09-07 下午11 58 36" src="https://user-images.githubusercontent.com/57031199/132375697-f7c23642-0954-4b9c-91bd-6a3918d8093b.png">
here is my code.

When I click Action 2, Chat. The onClick function cannot work.

**Comment by dericcain** [comment]
Could you provide a codesandbox with this issue please? I am going to close this for now but if you provide a codesandbox demonstrating the bug, then I will reopen it and we can address it.
